apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloud-run-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 1
        autoscaling.knative.dev/maxScale: 10
    spec:
      containers:
        - image: gcr.io/grid-assessor/cloud-run-demo:latest
          containers:
          - env:
            - name: NAME
              value: Hannah
          timeoutSeconds: 30
          resources:
            limits:
              cpu: 1
              memory: 1G
